### ISSUE TITLE
我也想学前端QAQ

### ISSUE THREAD

**Issue by mrzhqiang** [culing1317/web-demo-practice#1]
# 问题1
前端学习网站是啥？
# 问题2
前端需要了解哪些方面的技术？
# 问题3
前端待遇比之前高多少（N%）？

**Comment by mrzhqiang** [comment]
# Web IDE
1. [WebStorm](https://www.jetbrains.com/webstorm/)
2. [Atom](https://atom.io/)
3. [Sublime](https://www.sublimetext.com/)
以上排名按推荐优先级分布，其中 WebStorm 来自 IntelliJ IDEA 的出品方，业界神器，毫无疑问。Atom 来自 github 官方，飞速成长的开发神器，主要特点是生态环境吊炸天。Sublime 是老牌的开发神器，流畅，轻盈，简洁，所以值得拥有。

# About Node JS
目前在学习它，感觉前后端被它一统天下。React Native 则统一了移动端和 PC 端。好像 React Native 就是基于 Node JS 的，而 Vue 又基于 React JS...乱糟糟的。

**Comment by culing1317** [comment]
我现在用的IDE是VS Code
据leader讲，希望我们后面学nodejs，自己写接口，因为前端上手nodejs成本较小，使用的都是typescript， nodejs相比java来说优点是更轻量级，缺点是负载差，当数据较大并发量大时就基本歇菜了。
前端的知识很杂，使用的框架有很多，每个公司用的可能都不一样，，我现在用的是Angular，感觉还是很强大的。
css, sass, html, typescript, angular

**Comment by culing1317** [comment]
> # 问题1
> 前端学习网站是啥？
css, html, javascript [https://developer.mozilla.org/zh-CN/docs/Learn](url)
typescript  [https://www.tslang.cn/docs/home.html](url)
angular [https://angular.cn/docs](url)
> 
> # 问题2
> 前端需要了解哪些方面的技术？
css, html, javascript
选择使用的框架，angular、vue或其它
> 
> # 问题3
> 前端待遇比之前高多少（N%）？
前端的待遇与移动端相差无几，但是目前在苏州，移动端需求较少，前端急缺

**Comment by mrzhqiang** [comment]
> 我现在用的IDE是VS Code
> 据leader讲，希望我们后面学nodejs，自己写接口，因为前端上手nodejs成本较小，使用的都是typescript， nodejs相比java来说优点是更轻量级，缺点是负载差，当数据较大并发量大时就基本歇菜了。
> 前端的知识很杂，使用的框架有很多，每个公司用的可能都不一样，，我现在用的是Angular，感觉还是很强大的。
> css, sass, html, typescript, angular

# 回复 
1. 你有之前 MVVM 的经验，那么用 Angular JS 应该觉得很舒服；
2. 了解了一下 VS Code，它相对 Sublime 和 Atom 来说，插件和高效性提升了，但对比 WebStorm 还有一定的差距。参见 [原因](https://github.com/Microsoft/vscode/issues/19439)。WebStorm 和它的家族之所以没有流行的原因是因为：收费（可以永久破解），吃内存（对所有字符串和代码建立内存索引）；
3. 继续加油！！我现在也在搞前端了！

**Comment by mrzhqiang** [comment]
> > # 问题1
> > 前端学习网站是啥？
> > css, html, javascript [https://developer.mozilla.org/zh-CN/docs/Learn](url)
> > typescript  [https://www.tslang.cn/docs/home.html](url)
> > angular [https://angular.cn/docs](url)
> > # 问题2
> > 前端需要了解哪些方面的技术？
> > css, html, javascript
> > 选择使用的框架，angular、vue或其它
> > # 问题3
> > 前端待遇比之前高多少（N%）？
> > 前端的待遇与移动端相差无几，但是目前在苏州，移动端需求较少，前端急缺

# 回复
- 关于 [css, html, javascript](https://developer.mozilla.org/zh-CN/docs/Learn)
在距离创建这个提问 
![](https://user-images.githubusercontent.com/18276822/49996108-0ad46080-ffc9-11e8-95c2-93f0abd83591.png)
 之后的今天，我已恶补完 `HTML`、`CSS` 和 `JavaScript` 的相关基础知识，你提供的这个网页不错，我收藏后再查漏补缺。
- 关于 [typescript](https://www.tslang.cn/docs/home.html)
这个网址也不错呀，全面的查漏补缺，也可以了解到底什么是 `TypeScript`，以及它的发展历史。
- 关于 [angular](https://angular.cn/docs)
目前用的是 `Node.js`，它好像是 `JS` 的地基，打好基础再去学习 `Angular.js` 就事半功倍了；`Vue.js` 那些感觉也是一样的。
- 关于待遇
能在转方向的同时，拥有同等待遇真是不错。

**另：入手 `Node.js` 时架设了一个网站实例，目前正在生啃这个项目的源代码，也是一顿乱补服务器开发的知识，感觉这是一个非常非常深的坑，哈哈。**

**Comment by mrzhqiang** [comment]
> > # 问题1
> > 前端学习网站是啥？
> > css, html, javascript [https://developer.mozilla.org/zh-CN/docs/Learn](url)
> > typescript  [https://www.tslang.cn/docs/home.html](url)
> > angular [https://angular.cn/docs](url)
> > # 问题2
> > 前端需要了解哪些方面的技术？
> > css, html, javascript
> > 选择使用的框架，angular、vue或其它
> > # 问题3
> > 前端待遇比之前高多少（N%）？
> > 前端的待遇与移动端相差无几，但是目前在苏州，移动端需求较少，前端急缺

# 回复
- 关于 [css, html, javascript](https://developer.mozilla.org/zh-CN/docs/Learn)
在距离创建这个提问 
![](https://user-images.githubusercontent.com/18276822/49996108-0ad46080-ffc9-11e8-95c2-93f0abd83591.png)
 之后的今天，我已恶补完 `HTML`、`CSS` 和 `JavaScript` 的相关基础知识，你提供的这个网页不错，我收藏后再查漏补缺。
- 关于 [typescript](https://www.tslang.cn/docs/home.html)
这个网址也不错呀，全面的查漏补缺，也可以了解到底什么是 `TypeScript`，以及它的发展历史。
- 关于 [angular](https://angular.cn/docs)
目前用的是 `Node.js`，它好像是 `JS` 的地基，打好基础再去学习 `Angular.js` 就事半功倍了；`Vue.js` 那些感觉也是一样的。
- 关于待遇
能在转方向的同时，拥有同等待遇真是不错。

**另：入手 `Node.js` 时架设了一个[网站实例](http://bbs.randall.top)，目前正在生啃这个项目的源代码，也是一顿乱补服务器开发的知识，感觉这是一个非常非常深的坑，哈哈。**

**Comment by mrzhqiang** [comment]
Chat end...
